# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.9.0 on Tue Jan  5 20:00:28 2021
# Model: Sediment Delivery Ratio Model (SDR)

import logging
import sys

import natcap.invest.sdr.sdr
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = {
    'biophysical_table_path': 'C:/folder/biophysical_table.csv',
    'dem_path': 'C:/folder/dem.tif',
    'drainage_path': '',
    'erodibility_path': 'C:/folder/erodibility.tif',
    'erosivity_path': 'C:/folder/erosivity.tif',
    'ic_0_param': '0.5',
    'k_param': '0.9',
    'lulc_path': 'C:/folder/lulc.tif',
    'results_suffix': 'results',
    'sdr_max': '0.8',
    'threshold_flow_accumulation': '150',
    'watersheds_path': 'C:/folder/watershed.shp',
    'workspace_dir': 'C:/folder/calibration'
}

#Set the values for the k and IC0 calibration parameters and the years used for calibration

years = [2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]
kparam = [2, 1.5, 1.4, 1.3, 1.2, 1.1, 1, 0.9, 0.8, 0.7, 0.6, 0.5]
ICparam = [0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2]

###Use a “for” loop to change the arguments (k, IC, and years)

#Varying k and IC0 together

for k in kparam :
    args['k_param'] = k
    for ic in ICparam :
        args['ic_0_param'] = ic
        for year in years :
            lulc = 'C:/folder/lulc_' + str(year) + '.tif'
            erosivity = 'C:/folder/erosivity_' + str(year) + '.tif'
            args['lulc_path'] = lulc
            args['erosivity_path'] = erosivity
            args['results_suffix'] = 'year' + str(year) + '_' + str(k) + '_' + str(ic)
            if __name__ == '__main__':
                natcap.invest.sdr.sdr.execute(args)

#Varying only IC0 (or k)
#For varying only k, change ‘ic_0_param’ to ‘k_param’, ICparam to kparam, and ic to k 

for ic in ICparam :
    args['ic_0_param'] = ic
    for year in years :
        lulc = 'C:/folder/lulc_' + str(year) + '.tif'
        erosivity = 'C:/folder/erosivity_' + str(year) + '.tif'
        args['lulc_path'] = lulc
        args['erosivity_path'] = erosivity
        args['results_suffix'] = 'year' + str(year) + '_' + str(ic)
        if __name__ == '__main__':
            natcap.invest.sdr.sdr.execute(args)
